# Generated by Django 2.2.3 on 2019-07-17 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_Reg', models.CharField(max_length=100)),
                ('Bus_Name', models.CharField(max_length=100)),
                ('From', models.CharField(max_length=35)),
                ('To', models.CharField(max_length=35)),
                ('Dep_Date', models.DateField(max_length=100)),
                ('Dep_Time', models.TimeField(max_length=100)),
                ('Bus_Type', models.CharField(max_length=35)),
                ('Bus_Class', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('User_Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=35)),
                ('Mob_Number', models.CharField(max_length=35)),
                ('Payment_Type', models.CharField(max_length=35)),
                ('Account_Number', models.IntegerField(max_length=100)),
                ('User_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.SignUp')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=500)),
                ('User_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.SignUp')),
            ],
        ),
        migrations.CreateModel(
            name='BusSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seats_Name', models.CharField(max_length=200)),
                ('Bus_Reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.Bus')),
            ],
        ),
    ]
