# Generated by Django 2.2.3 on 2019-07-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20190717_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=100)),
                ('To', models.CharField(max_length=100)),
                ('Dep_Date', models.CharField(max_length=100)),
                ('Bus_Type', models.CharField(max_length=35)),
            ],
        ),
        migrations.AlterField(
            model_name='bus',
            name='Dep_Date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bus',
            name='Dep_Time',
            field=models.CharField(max_length=100),
        ),
    ]
