# Generated by Django 2.2.3 on 2019-07-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20190728_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='Dep_Date',
        ),
    ]
