# Generated by Django 2.2.3 on 2019-07-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_remove_bus_dep_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='Dep_Date',
        ),
    ]
