# Generated by Django 2.2.3 on 2019-07-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_remove_search_dep_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
